# Generated by Django 2.2 on 2019-10-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FW', 'Flowers'), ('MC', 'MarioCartridges'), ('DV', 'Dank Vapes'), ('BKI', 'BRASS KNUCKLE Indica'), ('BKS', 'BRASS KNUCKLE Sativa'), ('BKH', 'BRASS KNUCKLE Hybrid'), ('RV', 'ROVE'), ('FV', 'FLAVRX'), ('AL', 'ALPINES'), ('KP', 'KINGPENS'), ('HH1', 'HEAVY HITER 1g'), ('HH2', 'HEAVY HITTERS 2.2g')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('I', 'Indica'), ('S', 'Sativa'), ('H', 'Hybrid')], max_length=1),
        ),
    ]
