# Generated by Django 2.2 on 2019-10-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191030_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FW', 'Flowers'), ('MC', 'Mario Cartridges'), ('DV', 'Dank Vapes'), ('BKI', 'BRASS KNUCKLE Indica'), ('BKS', 'BRASS KNUCKLE Sativa'), ('BKH', 'BRASS KNUCKLE Hybrid'), ('RV', 'ROVE'), ('FV', 'FLAVRX'), ('AL', 'ALPINES'), ('KP', 'KINGPENS'), ('HH1', 'HEAVY HITER 1g'), ('HH2', 'HEAVY HITTERS 2.2g')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
    ]
