# Generated by Django 2.2 on 2019-11-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191111_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='label',
        ),
    ]
